### ISSUE TITLE
SSL 을 등록합니다.

### ISSUE THREAD

**Issue by rest515** [parti-coop/archives#14]
- [x] aws beanstalk 구성에서 load balancer를 선택하여 certificate를 등록합니다.
- [x] cloudflare에서 http page rewrite를 구성합니다.

**Comment by iamswain25** [comment]
단일 인스턴스에서 로드밸런싱으로 변경하니 application load balancer가 아닌 classic load balancer가 
뜨네요.. 예전에 eb cli 명령어로 환경 생성했을 때도 classic load balancer가 떠서 지우고 콘솔로 들어가서 새로 생성했었습니다. classic 에서 application으로 변경할 수 있는 방법이 있는지 모르겠어요..

**Comment by dalikim** [comment]
마그레이션은 안되요. 새로 복제해서 만들께요. https://stackoverflow.com/questions/50400631/how-to-convert-elastic-beanstalk-classic-load-balancer-to-application-load-balan

**Comment by dalikim** [comment]
완료했습니다.
