### ISSUE TITLE
사이트 연결이 되지 않고, 로그인이 안되는 문제를 해결합니다.

### ISSUE THREAD

**Issue by Mee-parti** [parti-coop/archives#15]
<img width="733" alt="스크린샷 2020-05-11 오전 9 59 36" src="https://user-images.githubusercontent.com/58237640/81515258-22567b00-936e-11ea-9ca1-59ce48292ffa.png">
지난주 금요일부터 http://archives.ws/ 사이트가 연결되지 않는 상황이고, 로그인도 안되었습니다.
문제 해결을 어떻게 하면 할 수 있을까요?

**Comment by iamswain25** [comment]
https://archives.ws/
제가 재설정할 때 테스트 한다고 https로 리다이렉선 설정을 꺼놓았네요 ㅜ 지금 다시 켜놓았습니다!

**Comment by Mee-parti** [comment]
@iamswain25 감사해요. 사이트 연결과 로그인 잘 됩니다.
